#!/bin/bash

# Valid Script
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/Guesswho44/izinsc/main/izin"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/6283877140463"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    sleep 5
    reboot
  fi
}
checking_sc

        # Color variables
        green="\e[38;5;82m"
        red="\e[38;5;196m"
        neutral="\e[0m"
        orange="\e[38;5;130m"
        blue="\e[38;5;39m"
        yellow="\e[38;5;226m"
        purple="\e[38;5;141m"
        bold_white="\e[1;37m"
        reset="\e[0m"
        pink="\e[38;5;205m"
        
        # Fungsi untuk random warna gradient
rand_color() {
  colors=(16 22 28 34 40 46 52 58 64 70 76 82 88 94 100 106 112 118 124 130 136 142 148 154 160 166 172 178 184 190 196 202 208 214 220 226 232 238 244 250)
  echo "${colors[$RANDOM % ${#colors[@]}]}"
}

# Random warna untuk header dan garis
color1=$(rand_color)
color2=$(rand_color)
color3=$(rand_color)
header_bg="\e[48;5;${color1}m"
text_p="\e[38;5;${color2}m"
text_color="\e[38;5;${color3}m"

        # Menentukan file log
        if [ -e "/var/log/auth.log" ]; then
            LOG_FILE="/var/log/auth.log"
        elif [ -e "/var/log/secure" ]; then
            LOG_FILE="/var/log/secure"
        else
            echo "File not exist"
            exit 1
        fi

        # Membuat file temporary
        touch /tmp/ssh_login_user

        clear

        # Fungsi untuk menampilkan informasi login SSH dan Dropbear
        tampilkan_info_ssh_dropbear() {

            echo -e "${orange}─────────────────────────────────────────${neutral}"
            echo -e "${green}         SSH USER LOGIN ACCOUNTS ${neutral}"
            echo -e "${orange}─────────────────────────────────────────${neutral}"
            echo -e "${orange}─────────────────────────────────────────${neutral}"
            printf " %-12s | %-7s | %-7s\n" "Username" "LoginIP" "LimitIP"
            echo -e "${orange}─────────────────────────────────────────${neutral}"

            cat $LOG_FILE | grep -i sshd | grep -i "Accepted password for" >/tmp/login-db-ssh.txt
            cat $LOG_FILE | grep -i dropbear | grep -i "Password auth succeeded" >/tmp/login-db-dropbear.txt

            ssh_pids=($(pgrep sshd))
            dropbear_pids=($(pgrep dropbear))

            for ssh_pid in "${ssh_pids[@]}"; do
                if grep -q "sshd\[$ssh_pid\]" /tmp/login-db-ssh.txt; then
                    grep "sshd\[$ssh_pid\]" /tmp/login-db-ssh.txt >/tmp/login-db-pid-ssh.txt
                    ssh_num=$(wc -l </tmp/login-db-pid-ssh.txt)
                    ssh_user=$(grep -oP '(?<=for )\w+' /tmp/login-db-pid-ssh.txt)
                    ssh_ip=$(grep -oP '(?<=from )\d+\.\d+\.\d+\.\d+' /tmp/login-db-pid-ssh.txt)
                    echo "$ssh_pid $ssh_user $ssh_ip" >>/tmp/ssh_login_user
                fi
            done

            for dropbear_pid in "${dropbear_pids[@]}"; do
                if grep -q "dropbear\[$dropbear_pid\]" /tmp/login-db-dropbear.txt; then
                    grep "dropbear\[$dropbear_pid\]" /tmp/login-db-dropbear.txt >/tmp/login-db-pid-dropbear.txt
                    dropbear_num=$(wc -l </tmp/login-db-pid-dropbear.txt)
                    dropbear_user=$(grep -oP "(?<=for ')\w+(?=' from)" /tmp/login-db-pid-dropbear.txt | sed "s/'//g")
                    dropbear_ip=$(grep -oP '(?<=from )\d+\.\d+\.\d+\.\d+' /tmp/login-db-pid-dropbear.txt | cut -d ':' -f 1)
                    echo "$dropbear_pid $dropbear_user $dropbear_ip" >>/tmp/ssh_login_user
                fi
            done

            tampilkan_info_pengguna "/tmp/ssh_login_user"
        }

        tampilkan_info_pengguna() {
    local file=$1
    user_list=($(grep '^###' /etc/ssh/.ssh.db | awk '{print $2}' | sort -u))

    if [[ -s $file ]]; then
        for user in "${user_list[@]}"; do
            user_count=$(grep -cw "$user" "$file")
            if [[ $user_count -gt 0 ]]; then
                user_sessions=$(grep -w "$user" "$file" | awk '{print $2}' | wc -l)
                if [[ $user_sessions -gt 0 ]]; then
                    if [[ -e /etc/ssh/$user ]]; then
                        ip_limit=$(cat /etc/ssh/$user)

                        if [[ -z "$ip_limit" || "$ip_limit" -eq 0 ]]; then
                            ip_limit="Unlimited"
                        fi

                        total_ip_connect=$(grep -cw "$user" "$file")
                        
                        printf " %-12s | %-7s | %-9s\n" "$user" "$total_ip_connect" "$ip_limit"
                    fi
                fi
            fi
        done
    fi
    echo -e "${orange}─────────────────────────────────────────${neutral}"
}

        # Menampilkan informasi
        tampilkan_info_ssh_dropbear

        # Membersihkan file temporary
        rm -rf /tmp/ssh_login_user /tmp/login-db-ssh.txt /tmp/login-db-dropbear.txt /tmp/login-db-pid-ssh.txt /tmp/login-db-pid-dropbear.txt
        echo " "
        read -n 1 -s -r -p "Press [ Enter ] to back on menu"
        menu
    