#!/bin/bash

# Valid Script
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/Guesswho44/izinsc/main/izin"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/6283877140463"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    sleep 5
    reboot
  fi
}
checking_sc

    
# Color variables
        green="\e[38;5;82m"
        red="\e[38;5;196m"
        neutral="\e[0m"
        orange="\e[38;5;130m"
        blue="\e[38;5;39m"
        yellow="\e[38;5;226m"
        purple="\e[38;5;141m"
        bold_white="\e[1;37m"
        reset="\e[0m"
        pink="\e[38;5;205m"
        dark_blue_bg="\e[48;5;18m"
        
        # Fungsi untuk random warna gradient
rand_color() {
  colors=(16 22 28 34 40 46 52 58 64 70 76 82 88 94 100 106 112 118 124 130 136 142 148 154 160 166 172 178 184 190 196 202 208 214 220 226 232 238 244 250)
  echo "${colors[$RANDOM % ${#colors[@]}]}"
}

# Random warna untuk header dan garis
color1=$(rand_color)
color2=$(rand_color)
color3=$(rand_color)
header_bg="\e[48;5;${color1}m"
text_color="\e[38;5;${color3}m"

convert_size() {
    local -i bytes=$1
    if [[ $bytes -lt 1024 ]]; then
        echo "${bytes}B"
    elif [[ $bytes -lt 1048576 ]]; then
        echo "$(((bytes + 1023) / 1024))KB"
    elif [[ $bytes -lt 1073741824 ]]; then
        echo "$(((bytes + 1048575) / 1048576))MB"
    else
        echo "$(((bytes + 1073741823) / 1073741824))GB"
    fi
}

# Function to print rainbow text
        print_rainbow() {
            local text="$1"
    local length=${#text}
    local start_color=(0 5 0)   # kuning gelap
    local mid_color=(255 255 0)     # kuning terang
    local end_color=(0 5 0)     # kuning gelap

    for ((i = 0; i < length; i++)); do
        local progress=$((i * 100 / (length - 1)))
        if [ $progress -lt 50 ]; then
            local factor=$((progress * 2))
            r=$(( (start_color[0] * (100 - factor) + mid_color[0] * factor) / 100 ))
            g=$(( (start_color[1] * (100 - factor) + mid_color[1] * factor) / 100 ))
            b=$(( (start_color[2] * (100 - factor) + mid_color[2] * factor) / 100 ))
        else
            local factor=$(((progress - 50) * 2))
            r=$(( (mid_color[0] * (100 - factor) + end_color[0] * factor) / 100 ))
            g=$(( (mid_color[1] * (100 - factor) + end_color[1] * factor) / 100 ))
            b=$(( (mid_color[2] * (100 - factor) + end_color[2] * factor) / 100 ))
        fi
        printf "\e[38;2;%d;%d;%dm%s" "$r" "$g" "$b" "${text:$i:1}"
    done
    echo -e "$reset"
}

vmess_members() {
    clear
    echo -e "${orange}─────────────────────────────────────────${neutral}"
    echo -e "      ${green}      VMESS MEMBERS  ${neutral}"
    echo -e "${orange}─────────────────────────────────────────${neutral}"

    if [ ! -e "/etc/xray/vmess/.vmess.db" ]; then
        echo -e "   ${red}No VMESS accounts registered.${neutral}"
        echo -e "${orange}─────────────────────────────────────────${neutral}"
        echo -e "   Press enter to return to the menu"
        read
        return
    fi

    echo -e " List of VMESS Accounts:"
    echo "┌──┬────────────┬──────┬────────────┬──────┬───┬──────┐"
    echo "│No│ Username   │ Exp  │ Exp Date   │Quota │IP │Usage │"
    echo "├──┼────────────┼──────┼────────────┼──────┼───┼──────┤"

    grep -E "^### " "/etc/xray/vmess/.vmess.db" | nl -s ' ' | while read -r line; do
        no=$(echo "$line" | awk '{print $1}')
        user=$(echo "$line" | awk '{print $3}')
        exp_date=$(echo "$line" | awk '{print $4}')
        
        current_timestamp=$(date +%s)
        exp_timestamp=$(date -d "$exp_date" +%s)
        days_left=$(( (exp_timestamp - current_timestamp) / 86400 ))
        if [ $days_left -lt 0 ]; then
            days_left=0
        fi
        exp="${days_left}d"

        quota_file="/etc/xray/vmess/${user}"
        ip_limit_file="/etc/xray/vmess/${user}IP"
        usage_file="/etc/xray/vmess/usage/${user}"

        quota="Unltd"
        if [ -f "$quota_file" ]; then
            quota=$(cat "$quota_file")
            if [ "$quota" != "" ] && [ "$quota" != "0" ]; then
                quota=$(convert_size "$quota")
            else
                quota="Unltd"
            fi
        fi

        ip_limit="Unltd"
        if [ -f "$ip_limit_file" ]; then
            ip_limit=$(cat "$ip_limit_file")
            if [ "$ip_limit" = "" ] || [ "$ip_limit" = "0" ]; then
                ip_limit="Unltd"
            fi
        fi

        usage="0GB"
        if [ -f "$usage_file" ]; then
            usage=$(cat "$usage_file")
            if [ "$usage" != "" ] && [ "$usage" != "0" ]; then
                usage=$(convert_size "$usage")
            else
                usage="0GB"
            fi
        fi

        printf "│%-2s│%-12s│%-6s│%-12s│%-6s│%-3s│%-6s│\n" "$no" "$user" "$exp" "$exp_date" "$quota" "$ip_limit" "$usage"
    done
    echo "└──┴────────────┴──────┴────────────┴──────┴───┴──────┘"

    echo -e "   Press enter to return to menu"
    read
}

change_vmess_limit() {
    clear
    echo -e "${orange}─────────────────────────────────────────${neutral}"
    echo -e "    ${green}      CHANGE VMESS LIMIT  ${neutral}"
    echo -e "${orange}─────────────────────────────────────────${neutral}"


    if [ ! -e "/etc/xray/vmess/.vmess.db" ]; then
        echo -e "   ${red}No VMESS accounts registered.${neutral}"
        echo -e "${orange}─────────────────────────────────────────${neutral}"
        echo -e "   Press enter to return to the menu"
        read
        return
    fi
    echo -e "   List of VMESS Accounts:"
    echo -e "${orange}─────────────────────────────────────────${neutral}"
    account_count=$(grep -cE "^### " "/etc/xray/vmess/.vmess.db")
    if [ $account_count -eq 0 ]; then
        echo -e "   ${red}No active VMESS accounts.${neutral}"
        echo -e "${orange}─────────────────────────────────────────${neutral}"
        echo -e "   Press enter to return to the menu"
        read
        return
    fi

    echo "┌────┬────────────────────┬─────────────┐"
    echo "│ no │ username           │     exp     │"
    echo "├────┼────────────────────┼─────────────┤"
    grep -E "^### " "/etc/xray/vmess/.vmess.db" | awk '{
        cmd = "date -d \"" $3 "\" +%s"
        cmd | getline exp_timestamp
        close(cmd)
        current_timestamp = systime()
        days_left = int((exp_timestamp - current_timestamp) / 86400)
        if (days_left < 0) days_left = 0
        printf "│ %-2d │ %-18s │ %-11s │\n", NR, $2, days_left " days"
    }'
    echo "└────┴────────────────────┴─────────────┘"

    echo -e "${orange}─────────────────────────────────────────${neutral}"
    read -p "   Select the account number : " account_number
    
    # Check if input is a number
    if ! [[ "$account_number" =~ ^[0-9]+$ ]]; then
        echo -e "   ${red}Error: Input must be a number.${neutral}"
        echo -e "   Press enter to return to the menu"
        read
        return
    fi
    
    # Check if account number is valid
    if [ "$account_number" -lt 1 ] || [ "$account_number" -gt "$account_count" ]; then
        echo -e "   ${red}Error: Invalid account number.${neutral}"
        echo -e "   Press enter to return to the menu"
        read
        return
    fi

    username=$(grep -E "^### " "/etc/xray/vmess/.vmess.db" | cut -d ' ' -f 2 | sed -n "${account_number}p")

    if [ -z "$username" ]; then
        echo -e "   ${red}Invalid account number.${neutral}"
        echo -e "   Press enter to return to menu"
        read
        return
    fi

    echo -e "Changing limit for account: ${green}$username${neutral}"
    read -p "Enter new quota limit (in GB, 0 for unlimited): " new_quota
    read -p "Enter new IP limit (0 for unlimited): " new_ip_limit

    # Validate input
    if ! [[ "$new_quota" =~ ^[0-9]+$ ]]; then
        echo -e "${red}Error: Quota limit must be a number.${neutral}"
        echo -e "   Press enter to return to the menu"
        read
        return
    fi

    if ! [[ "$new_ip_limit" =~ ^[0-9]+$ ]]; then
        echo -e "${red}Error: IP limit must be a number.${neutral}"
        echo -e "   Press enter to return to the menu"
        read
        return
    fi

    # Convert quota to bytes
    new_quota_bytes=$((new_quota * 1024 * 1024 * 1024))

    # Update quota and IP limit files
    echo "${new_quota_bytes}" >"/etc/xray/vmess/${username}"
    echo "${new_ip_limit}" >"/etc/xray/vmess/${username}IP"

    # Check if update was successful
    if [ $? -eq 0 ]; then
        echo -e "${green}Limit for account $username successfully changed.${neutral}"
        echo -e "New quota: ${new_quota} GB"
        echo -e "New IP limit: ${new_ip_limit}"
    else
        echo -e "${red}Failed to change limit for account $username.${neutral}"
        echo -e "Please ensure you have sufficient permissions and try again."
    fi

    echo -e "${orange}─────────────────────────────────────────${neutral}"
    echo -e "   Press enter to return to menu"
    read
}

vmess_details() {
    clear
    echo -e "${orange}─────────────────────────────────────────${neutral}"
    echo -e "      ${green}      VMESS DETAIL  ${neutral}"
    echo -e "${orange}─────────────────────────────────────────${neutral}"

    if [ ! -e "/etc/xray/vmess/.vmess.db" ]; then
        echo -e "   ${red}No VMESS accounts registered.${neutral}"
        echo -e "   ${orange}─────────────────────────────────────────${neutral}"
        echo -e "   Press enter to return to menu"
        read
        return
    fi

    echo -e "   List of VMESS Accounts:"
    echo -e "${orange}─────────────────────────────────────────${neutral}"

    while IFS= read -r line; do
        user=$(echo $line | cut -d ' ' -f 2 | sort -u)
        exp=$(echo $line | cut -d ' ' -f 3 | sort -u)
        uuid=$(echo $line | cut -d ' ' -f 4 | sort -u)

        echo -e "   Username      : ${green}$user${neutral}"
        echo -e "   Expired Date  : ${green}$exp${neutral}"
        echo -e "   UUID          : ${green}$uuid${neutral}"

        if [ -f "/etc/xray/vmess/${user}" ]; then
            quota=$(cat /etc/xray/vmess/${user})
            if [ -n "$quota" ] && [ "$quota" != "0" ]; then
                quota_readable=$(convert_size $quota)
                echo -e "   Quota         : ${green}$quota_readable${neutral}"
            else
                echo -e "   Quota         : ${green}Unlimited${neutral}"
            fi
        else
            echo -e "   Quota         : ${green}Unlimited${neutral}"
        fi

        if [ -f "/etc/xray/vmess/${user}IP" ]; then
            ip_limit=$(cat /etc/xray/vmess/${user}IP)
            if [ -n "$ip_limit" ] && [ "$ip_limit" != "0" ]; then
                echo -e "   IP Limit      : ${green}$ip_limit${neutral}"
            else
                echo -e "   IP Limit      : ${green}Unlimited${neutral}"
            fi
        else
            echo -e "   IP Limit      : ${green}Unlimited${neutral}"
        fi

        echo -e "${orange}─────────────────────────────────────────${neutral}"
    done <"/etc/xray/vmess/.vmess.db"

    echo -e "   Press enter to return to menu"
    read
}
custom_vmess_uuid() {
    clear
    echo -e "${orange}─────────────────────────────────────────${neutral}"
    echo -e "     ${green}      CUSTOM VMESS UUID  ${neutral}"
    echo -e "${orange}─────────────────────────────────────────${neutral}"


    if [ ! -e "/etc/xray/vmess/.vmess.db" ]; then
        echo -e "   ${red}No VMESS accounts registered.${neutral}"
        echo -e "${orange}─────────────────────────────────────────${neutral}"
        echo -e "   Press enter to return to the menu"
        read
        return
    fi

    account_count=$(grep -cE "^### " "/etc/xray/vmess/.vmess.db")
    if [ $account_count -eq 0 ]; then
        echo -e "   ${red}No active VMESS accounts.${neutral}"
        echo -e "${orange}─────────────────────────────────────────${neutral}"
        echo -e "   Press enter to return to the menu"
        read
        return
    fi
    echo -e " List of VMESS Accounts:"
    echo -e "${orange}─────────────────────────────────────────${neutral}"
    echo "┌────┬────────────────────┬─────────────┐"
    echo "│ no │ username           │     exp     │"
    echo "├────┼────────────────────┼─────────────┤"
    grep -E "^### " "/etc/xray/vmess/.vmess.db" | awk '{
        cmd = "date -d \"" $3 "\" +%s"
        cmd | getline exp_timestamp
        close(cmd)
        current_timestamp = systime()
        days_left = int((exp_timestamp - current_timestamp) / 86400)
        if (days_left < 0) days_left = 0
        printf "│ %-2d │ %-18s │ %-11s │\n", NR, $2, days_left " days"
    }'
    echo "└────┴────────────────────┴─────────────┘"

    echo -e "${orange}─────────────────────────────────────────${neutral}"
    read -p "   Select the account number : " account_number
    
    # Check if input is a number
    if ! [[ "$account_number" =~ ^[0-9]+$ ]]; then
        echo -e "   ${red}Error: Input must be a number.${neutral}"
        echo -e "   Press enter to return to the menu"
        read
        return
    fi
    
    # Check if account number is valid
    if [ "$account_number" -lt 1 ] || [ "$account_number" -gt "$account_count" ]; then
        echo -e "   ${red}Error: Invalid account number.${neutral}"
        echo -e "   Press enter to return to the menu"
        read
        return
    fi

    user=$(grep -E "^### " "/etc/xray/vmess/.vmess.db" | cut -d ' ' -f 2 | sed -n "${account_number}p")

    if [ -z "$user" ]; then
        echo -e "   ${red}Invalid account number.${neutral}"
        echo -e "   Press enter to return to menu"
        read
        return
    fi
    while true; do
        read -p "   UUID (min 6 characters): " new_uuid
        if [[ ${#new_uuid} -ge 6 && "$new_uuid" =~ ^[a-zA-Z0-9_-]+$ ]]; then
            break
        else
            printf "\033[1A\033[0J"
            echo -e "${red}   UUID must be at least 6 characters${neutral}"
        fi
    done

    if [ -z "$new_uuid" ]; then
        echo -e "${red}Error: UUID cannot be empty.${neutral}"
        echo -e "   Press enter to return to menu"
        read
        return
    fi

    # Update UUID in config.json
    user_data=$(cat /etc/xray/vmess/.vmess.db | grep "^### $user")
    exp=$(echo "$user_data" | awk '{print $3}')
    config_file="/etc/xray/vmess/config.json"
    db_file="/etc/xray/vmess/.vmess.db"

    sed -i "/^### $user $exp/,/^},{/d" "$config_file"

    # Add configuration back to config_file
    sed -i '/#vmess$/a\### '"$user $exp"'\
},{"id": "'""$new_uuid""'","email": "'""$user""'"'  "$config_file"

    sed -i '/#vmessgrpc$/a\### '"$user $exp"'\
},{"id": "'""$new_uuid""'","email": "'""$user""'"'  "$config_file"
  
    sed -i "/^### $user/d" "$db_file"
    echo "### $user $exp $new_uuid" >> "$db_file"
    systemctl restart vmess@config

    if [ $? -eq 0 ]; then
        echo -e "UUID for account ${green}$user${neutral} successfully changed."
    else
        echo -e "${red}Failed to change UUID for account $user.${neutral}"
        echo -e "Please ensure you have sufficient permissions and try again."
    fi

    echo -e "${orange}─────────────────────────────────────────${neutral}"
    echo -e "   Press enter to return to menu"
    read
}
print_names() {
    local text="$1"
    local length=${#text}
    local start_color=(200 200 0)  # Kuning gelap
    local mid_color=(255 255 0)    # Kuning terang
    local end_color=(200 200 0)    # Kuning gelap

    for ((i = 0; i < length; i++)); do
        local progress=$((i * 100 / (length - 1)))

        if [ $progress -lt 50 ]; then
            local factor=$((progress * 2))
            r=$(( (start_color[0] * (100 - factor) + mid_color[0] * factor) / 100 ))
            g=$(( (start_color[1] * (100 - factor) + mid_color[1] * factor) / 100 ))
            b=$(( (start_color[2] * (100 - factor) + mid_color[2] * factor) / 100 ))
        else
            local factor=$(((progress - 50) * 2))
            r=$(( (mid_color[0] * (100 - factor) + end_color[0] * factor) / 100 ))
            g=$(( (mid_color[1] * (100 - factor) + end_color[1] * factor) / 100 ))
            b=$(( (mid_color[2] * (100 - factor) + end_color[2] * factor) / 100 ))
        fi

        printf "\e[38;2;%d;%d;%dm%s" "$r" "$g" "$b" "${text:$i:1}"
    done
    echo -e "\e[0m" # Reset warna
}
# Function to display VMESS menu
display_vmess_menu() {
    clear
echo -e "${orange}────────────────────────────────────────${neutral}"
echo -e "${dark_blue_bg}${green}           MENU VMESS MANAGER           ${neutral}   "
echo -e "${orange}────────────────────────────────────────${neutral}"
echo -e "  ${green}[1]${neutral}  $(print_names "Create Vmess Account")"
echo -e "  ${green}[2]${neutral}  $(print_names "Delete Vmess Account")"
echo -e "  ${green}[3]${neutral}  $(print_names "Renew Vmess Account")"
echo -e "  ${green}[4]${neutral}  $(print_names "Check Vmess Login Account")"
echo -e "  ${green}[5]${neutral}  $(print_names "List Vmess Members")"
echo -e "  ${green}[6]${neutral}  $(print_names "Change Vmess Account Limit")"
echo -e "  ${green}[7]${neutral}  $(print_names "View Vmess Account Details")"
echo -e "  ${green}[8]${neutral}  $(print_names "Create Trial Vmess Account")"
echo -e "  ${green}[9]${neutral}  $(print_names "Custom Vmess UUID")"
echo -e "  ${green}[x]${neutral}  $(print_names "Exit Vmess Manager")"
echo -e "${orange}────────────────────────────────────────${neutral}"
print_rainbow "────────────────────────────────────────"
    echo -e "           ${orange}───${green}───${yellow}───${blue}───${purple}───${red}───${neutral}"
    echo -e ""
    read -p "Pick a number (1-9) or hit 'x' to bail: " vmess_choice

    case $vmess_choice in
    1) addvmess ;;
    2) dellvmess ;;
    3) renewvmess ;;
    4) checkvmess ;;
    5) vmess_members ;;
    6) change_vmess_limit ;;
    7) vmess_details ;;
    8) trialvmess ;;
    9) custom_vmess_uuid ;;
    x | X)
        echo -e ""
        echo -e "   ${green}Thank you for using our service.${neutral}"
        exit 0
        ;;
    *)
        echo -e "   ${red}Invalid choice. Please try again.${neutral}"
        sleep 2
        display_vmess_menu
        ;;
    esac
}

# Call function to display menu
display_vmess_menu
